# Generated by Django 5.0.7 on 2024-08-05 07:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdieme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('montant', models.IntegerField()),
                ('date_transaction', models.DateField()),
                ('code_transaction_numero_bordereau', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typemateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_materel', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(default=datetime.datetime.now, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('grade', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('date_enre', models.DateField(default=datetime.datetime.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerdiemeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('perdieme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.perdieme')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='perdieme',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.personnel'),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100, null=True)),
                ('lieu', models.CharField(max_length=100, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField()),
                ('description_projet', models.CharField(max_length=100, null=True)),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='perdieme',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.projet'),
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_rapport', models.CharField(max_length=150, null=True)),
                ('description_file', models.FileField(null=True, upload_to='documents/')),
                ('date', models.DateField()),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.personnel')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=100, null=True)),
                ('quantite_materiel', models.CharField(max_length=100, null=True)),
                ('qualite', models.CharField(max_length=100, null=True)),
                ('date_d_enregistrement', models.DateField(null=True)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.projet')),
                ('type_materiel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.typemateriel')),
            ],
        ),
    ]
