# Generated by Django 5.0.7 on 2024-09-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_personnel_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='description_file',
        ),
        migrations.AddField(
            model_name='rapport',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
