# Generated by Django 5.0.7 on 2024-09-09 11:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_rapport_description_file_rapport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
