# Generated by Django 5.0.7 on 2024-09-09 11:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_rapport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True),
        ),
    ]
