# Generated by Django 5.0.7 on 2024-09-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_rapport_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='grade',
        ),
        migrations.AddField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('Chef', 'Chef'), ('Responsable', 'Responsable'), ('Technicien', 'Technicien')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
    ]
