# Generated by Django 5.0.7 on 2024-09-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_personnel_grade_personnel_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='n_est_pas_valide',
            field=models.BooleanField(default=False),
        ),
    ]
