# Generated by Django 5.0.7 on 2024-09-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rapport_n_est_pas_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='est_valide',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='n_est_pas_valide',
        ),
        migrations.AddField(
            model_name='rapport',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
