# Generated by Django 5.0.7 on 2024-09-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_rapport_est_valide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='statut',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('En attente', 'En attente de validation'), ('Valide', 'Validé'), ('Refuse', 'Refusé')], default='Brouillon', max_length=10),
        ),
    ]
