# Generated by Django 5.0.7 on 2024-09-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rapport_est_valide_alter_rapport_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='est_valide',
        ),
    ]
