# Generated by Django 4.0 on 2024-10-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_rapport_est_valide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=100, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='perdieme',
            old_name='personnel',
            new_name='personne_receveur',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='chef_projet',
            new_name='responsable_projet',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='perdieme',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='projet',
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=100, null=True)),
                ('lieu', models.CharField(max_length=100, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField()),
                ('chef_d_equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.personnel')),
                ('finance_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.financement')),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.site'),
        ),
        migrations.AddField(
            model_name='perdieme',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.site'),
        ),
        migrations.AddField(
            model_name='projet',
            name='finance_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.financement'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.site'),
        ),
    ]
