# Generated by Django 4.0 on 2024-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_financement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('Choisisez', 'Choisisez'), ('Chef', 'Chef'), ('Responsable', 'Responsable'), ('Technicien', 'Technicien')], max_length=50, null=True),
        ),
    ]
